TMX_MAP_TAGS = {
    49: 'Altered Nadeo',
    40: 'Arena',
    34: 'Backwards',
    44: 'Bobsleigh',
    20: 'Bumper',
    13: 'Competitive',
    15: 'Dirt',
    42: 'Educational',
    24: 'Endurance',
    46: 'FlagRush',
    21: 'Fragile',
    48: 'Freeblocking',
    41: 'Freestyle',
    35: 'Freewheel',
    2: 'FullSpeed',
    33: 'Grass',
    14: 'Ice',
    23: 'Kacky',
    5: 'LOL',
    25: 'Mini',
    30: 'Minigame',
    27: 'Mixed',
    8: 'MultiLap',
    28: 'Nascar',
    31: 'Obstacle',
    9: 'Offroad',
    45: 'Pathfinding',
    39: 'Plastic',
    18: 'Platform',
    6: 'Press Forward',
    47: 'Puzzle',
    1: 'Race',
    17: 'Reactor',
    26: 'Remake',
    37: 'Royal',
    4: 'RPG',
    43: 'Sausage',
    22: 'Scenery',
    36: 'Signature',
    19: 'Slow Motion',
    29: 'SpeedDrift',
    12: 'SpeedFun',
    7: 'SpeedTech',
    16: 'Stunt',
    3: 'Tech',
    32: 'Transitional',
    10: 'Trial',
    38: 'Water',
    11: 'ZrT',
}